# Generated by Django 6.0.3 on 2026-03-12 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_bookmodels_categories_and_more"),
        ("likes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likemodel",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="books.userbookmodels",
            ),
        ),
    ]
