# Generated by Django 6.0.3 on 2026-03-12 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_bookmodels_categories_and_more"),
        ("likes", "0002_alter_likemodel_book"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="likemodel",
            name="likes_likem_user_id_6ef063_idx",
        ),
        migrations.RenameField(
            model_name="likemodel",
            old_name="book",
            new_name="user_book",
        ),
        migrations.AlterUniqueTogether(
            name="likemodel",
            unique_together={("user", "user_book")},
        ),
        migrations.AddIndex(
            model_name="likemodel",
            index=models.Index(
                fields=["user", "user_book"], name="likes_likem_user_id_9da4f9_idx"
            ),
        ),
    ]
