# Generated by Django 6.0 on 2026-01-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='userbook',
            options={'ordering': ['-created_at'], 'verbose_name': 'книгу пользователя', 'verbose_name_plural': 'Книги пользователей'},
        ),
        migrations.AlterField(
            model_name='book',
            name='google_id',
            field=models.CharField(default=123, max_length=50, unique=True, verbose_name='Google ID'),
            preserve_default=False,
        ),
    ]
