# Generated by Django 6.0.3 on 2026-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodels",
            name="categories",
            field=models.CharField(default="other", max_length=100),
        ),
        migrations.AlterField(
            model_name="bookmodels",
            name="cover_url",
            field=models.URLField(blank=True, default="other", verbose_name="Обложка"),
            preserve_default=False,
        ),
    ]
