# Generated by Django 6.0 on 2026-02-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_alter_userbook_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Жанры'),
        ),
    ]
