# Generated by Django 6.0 on 2026-02-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookModels',
        ),
    ]
